### ISSUE TITLE
Can it be installed into user tiddlywiki folder when using Node.js version?

### ISSUE THREAD

**Issue by onlyice** [felixhayashi/TW5-TiddlyMap#265]
I've noticed that the Node.js server version tw5 supports [PluginFolder](http://tiddlywiki.com/#PluginFolders) mechanism. Can TiddlyMap be installed in that way? I use Dropbox to sync the tiddlers among multiple computers, and it would be convenient to sync plugins as well.

For example, I've created a wiki folder in `~/wiki`, and I copied all the plugin files (exactly as the README says) into it:

```
wiki/
  - tiddlers/
    - many tid files...
    - plugins
      - felixhayashi
        - hotzone
        - tiddlymap
        - topstoryview
        - vis
        - maps
  - tiddlywiki.info
```

And when I run `tiddlywiki --server`, some error accured:

```
λ tiddlywiki --server 8000 --verbose                                                                                        
Serving on 127.0.0.1:8000                                                                                                   
(press ctrl-C to exit)                                                                                                      
Boot log:                                                                                                                   
  Startup task: load-modules                                                                                                
  Startup task: info after: load-modules before: startup                                                                    
  Startup task: startup after: load-modules                                                                                 
  Startup task: story after: startup                                                                                        
  Startup task: commands platforms: node after: story                                                                       
syncer-server-filesystem: Dispatching 'save' task: $:/StoryList                                                             
Error executing boot module $:/plugins/felixhayashi/tiddlymap/js/widget/MapWidget: {"code":"MODULE_NOT_FOUND"}              
                                                                                                                            
Error: Cannot find module '$:/plugins/felixhayashi/tiddlymap/js/lib/SelectionRectangle'                                     
    at Function.Module._resolveFilename (module.js:470:15)                                                                  
    at Function.Module._load (module.js:418:25)                                                                             
    at Module.require (module.js:498:17)                                                                                    
    at require (internal/module.js:20:19)                                                                                   
    at Object.$tw.modules.execute (C:\Users\onlyicelin\AppData\Roaming\npm\node_modules\tiddlywiki\boot\boot.js:720:11)     
    at require (C:\Users\onlyicelin\AppData\Roaming\npm\node_modules\tiddlywiki\boot\boot.js:679:24)                        
    at $:/plugins/felixhayashi/tiddlymap/js/widget/MapWidget:38:27                                                          
    at ContextifyScript.Script.runInContext (vm.js:32:29)                                                                   
    at ContextifyScript.Script.runInNewContext (vm.js:38:15)                                                                
    at Object.runInNewContext (vm.js:91:38)                                                                                 
```

Thanks in advanced.

**Comment by felixhayashi** [comment]
Hi @onlyice 
many apologies for the late reply.
yeah, this should work, but you need to make sure to place the contents of the `dist` folders of each plugin in the respective place in the folder structure described above and also make sure to also register those plugins in your tiddlywiki.info (see instructions: https://github.com/felixhayashi/TW5-TiddlyMap#installation). If this does not work, try to install some other tiddlywiki plugin and see if this works, if it doesn't maybe your general setup is not correct.
best wishes
felix

**Comment by gnsiva** [comment]
I had a similar problem, for anyone else who finds this, the plugins directory should have been one level up like the following

```
wiki/
  - tiddlers/
    - many tid files...
  - plugins
    - felixhayashi
      - hotzone
      - tiddlymap
      - topstoryview
      - vis
      - maps
  - tiddlywiki.info
```
