### ISSUE TITLE
TiddlyWiki build error

### ISSUE THREAD

**Issue by guillefix** [felixhayashi/TW5-TiddlyMap#275]
After upgrading to the latest version of TiddlyMap, I am getting this error when running `tiddlywiki --build`

```
$:/plugins/felixhayashi/tiddlymap/js/macro/tmap:10
var _EdgeType=require("$:/plugins/felixhayashi/tiddlymap/js/EdgeType");var _EdgeType2=_interopRequireDefault(_EdgeType);var _ViewAbstraction=require("$:/plugins/felixhayashi/tiddlymap/js/ViewAbstraction");var _ViewAbstraction2=_interopRequireDefault(_ViewAbstraction);var _utils=require("$:/plugins/felixhayashi/tiddlymap/js/utils");var _utils2=_interopRequireDefault(_utils);function _interopRequireDefault(e){return e&&e.__esModule?e:{default:e}}var name="tmap";var params=getParamSlots(5);function run(){this.substVarRefs=this.substituteVariableReferences;var e=command[arguments[0]];var t=null;if(typeof e==="function"){var r=Array.prototype.slice.call(arguments,1);t=e.apply(this,r)}return typeof t==="string"?t:""}function getParamSlots(e){var t=[];for(var r=0;r<e;r++){t.push({name:"arg"+r})}return t}var command=_utils2.default.makeHashMap();command.basename=function(e){var t=this.getVariable("currentTiddler");return _utils2.default.getBasename(t,e)};command.da

ReferenceError: $tm is not defined
    at MacroCallWidget.command.option ($:/plugins/felixhayashi/tiddlymap/js/macro/tmap:10:2686)
    at MacroCallWidget.run ($:/plugins/felixhayashi/tiddlymap/js/macro/tmap:10:675)
    at MacroCallWidget.Widget.evaluateMacroModule ($:/core/modules/widgets/widget.js:174:21)
    at MacroCallWidget.Widget.getVariable ($:/core/modules/widgets/widget.js:101:14)
    at MacroCallWidget.execute ($:/core/modules/widgets/macrocall.js:51:18)
    at MacroCallWidget.render ($:/core/modules/widgets/macrocall.js:32:7)
    at $:/core/modules/widgets/widget.js:348:15
    at Object.$tw.utils.each (/usr/lib/node_modules/tiddlywiki/boot/boot.js:69:12)
    at ElementWidget.Widget.renderChildren ($:/core/modules/widgets/widget.js:347:12)
    at ElementWidget.render ($:/core/modules/widgets/element.js:41:7)
```

**Comment by jbs-fm** [comment]
Experiencing the same issue, would add that I installed Tiddlymap using `Option 1 – Drag & drop installation`.

**Comment by felixhayashi** [comment]
Thanks for reporting @guillefix @jbs-fm didn't experience that myself but will have a closer look at it.

**Comment by felixhayashi** [comment]
I tested the node.js way (`tiddlywiki ./mywiki --build index`) and the drag and drop installation into an empty tiddlywiki (downloaded from tiddlywiki.com). Both ways work fine.

Which operating systems/browsers are you guys using? Can you confirm that building/starting from an empty wiki works fine?

**Comment by felixhayashi** [comment]
@guillefix maybe could you post the contents of your `tiddlywiki.info` file?

**Comment by felixhayashi** [comment]
@guillefix maybe after reinstallation the plugins were removed from your tiddlywiki plugin folder?

Did you check that your setup looks as described here:

* https://github.com/felixhayashi/TW5-TiddlyMap#installation
* https://groups.google.com/d/msg/tiddlywiki/5sIyj0h38pc/4Bb_whdfEAAJ

will close this issue now, feel free to add further comments regarding this issue.

**Comment by renyuneyun** [comment]
If I build the wiki using `tiddlywiki . --build index`, it will execute fine.

However, if do this without the `index` part (i.e. `tiddlywiki . --build`), it will fail with this error.

**Comment by obaltzer** [comment]
I am running into the same issues when trying to build the static pages. It seemingly only affects Tiddlers that reference the map widget:
```
$ tiddlywiki . --rendertiddlers 'WithWidget' '$:/core/templates/static.tiddler.html' static text/plain
[...]
ReferenceError: $tm is not defined
    at new t ($:/plugins/felixhayashi/tiddlymap/js/widget/MapWidget:11:258)
    at ElementWidget.Widget.makeChildWidget ($:/core/modules/widgets/widget.js:350:9)
    at $:/core/modules/widgets/widget.js:337:27
    at Object.$tw.utils.each (/home/oliver/Sync/Projects/reinsurance.dev/node_modules/tiddlywiki/boot/boot.js:126:12)
    at ElementWidget.Widget.makeChildWidgets ($:/core/modules/widgets/widget.js:336:12)
    at ElementWidget.execute ($:/core/modules/widgets/element.js:70:7)
    at ElementWidget.render ($:/core/modules/widgets/element.js:32:7)
    at TranscludeWidget.Widget.renderChildren ($:/core/modules/widgets/widget.js:390:15)
    at TranscludeWidget.render ($:/core/modules/widgets/transclude.js:33:7)
    at ListItemWidget.Widget.renderChildren ($:/core/modules/widgets/widget.js:390:15)
```

vs. Tiddlers without the map widget work just fine:

```
$ tiddlywiki . --rendertiddlers 'NoWidget' '$:/core/templates/static.tiddler.html' static text/plain
 syncer-server-filesystem: Dispatching 'save' task: $:/StoryList
```
On the other hand, building the single file `index.html` via `$:/plugins/tiddlywiki/tiddlyweb/save/offline` works just fine.

Versions:
* TiddlyWiki: 5.1.22
* TiddlyMap: 0.17.7+9982
